export const blogRelations: Record<string, string[]> = {
  "social-media-image-sizes-2026": [
    "best-image-format-for-social-media",
    "resize-image-without-stretching",
    "best-youtube-thumbnail-size",
    "how-to-watermark-images",
  ],
  "webp-vs-avif-vs-jpeg": [
    "jpg-vs-png",
    "compress-images-for-website-seo",
    "reduce-image-size-without-losing-quality",
    "best-image-format-for-social-media",
  ],
  "compress-images-for-website-seo": [
    "reduce-image-size-without-losing-quality",
    "webp-vs-avif-vs-jpeg",
    "resize-image-without-stretching",
    "jpg-vs-png",
  ],
  "resize-image-without-stretching": [
    "social-media-image-sizes-2026",
    "increase-image-resolution-ai",
    "compress-images-for-website-seo",
    "improve-image-quality-online",
  ],
  "make-transparent-background-png": [
    "remove-image-background-free",
    "how-to-create-youtube-thumbnail",
    "thumbnail-color-psychology",
    "best-image-format-for-social-media",
  ],
  "thumbnail-color-psychology": [
    "youtube-thumbnail-ab-testing",
    "what-makes-thumbnail-go-viral",
    "how-to-create-youtube-thumbnail",
    "best-youtube-thumbnail-size",
  ],
  "youtube-thumbnail-ab-testing": [
    "thumbnail-color-psychology",
    "what-makes-thumbnail-go-viral",
    "create-youtube-thumbnail-free",
    "canva-vs-pixores",
  ],
  "best-image-format-for-social-media": [
    "social-media-image-sizes-2026",
    "jpg-vs-png",
    "webp-vs-avif-vs-jpeg",
    "how-to-watermark-images",
  ],
  "how-to-watermark-images": [
    "best-image-format-for-social-media",
    "social-media-image-sizes-2026",
    "reduce-image-size-without-losing-quality",
    "create-youtube-thumbnail-free",
  ],
  "favicon-sizes-guide-2026": [
    "compress-images-for-website-seo",
    "webp-vs-avif-vs-jpeg",
    "jpg-vs-png",
    "reduce-image-size-without-losing-quality",
  ],
  "best-youtube-thumbnail-size": [
    "social-media-image-sizes-2026",
    "how-to-create-youtube-thumbnail",
    "thumbnail-color-psychology",
    "youtube-thumbnail-ab-testing",
  ],
  "how-to-create-youtube-thumbnail": [
    "thumbnail-color-psychology",
    "youtube-thumbnail-ab-testing",
    "best-youtube-thumbnail-size",
    "make-transparent-background-png",
  ],
  "remove-image-background-free": [
    "make-transparent-background-png",
    "how-to-create-youtube-thumbnail",
    "best-image-format-for-social-media",
    "improve-image-quality-online",
  ],
  "improve-image-quality-online": [
    "increase-image-resolution-ai",
    "resize-image-without-stretching",
    "reduce-image-size-without-losing-quality",
    "compress-images-for-website-seo",
  ],
  "increase-image-resolution-ai": [
    "improve-image-quality-online",
    "resize-image-without-stretching",
    "best-youtube-thumbnail-size",
    "compress-images-for-website-seo",
  ],
  "create-youtube-thumbnail-free": [
    "how-to-create-youtube-thumbnail",
    "thumbnail-color-psychology",
    "youtube-thumbnail-ab-testing",
    "canva-vs-pixores",
  ],
  "what-makes-thumbnail-go-viral": [
    "thumbnail-color-psychology",
    "youtube-thumbnail-ab-testing",
    "how-to-create-youtube-thumbnail",
    "best-youtube-thumbnail-size",
  ],
  "jpg-vs-png": [
    "webp-vs-avif-vs-jpeg",
    "best-image-format-for-social-media",
    "compress-images-for-website-seo",
    "reduce-image-size-without-losing-quality",
  ],
  "reduce-image-size-without-losing-quality": [
    "compress-images-for-website-seo",
    "webp-vs-avif-vs-jpeg",
    "resize-image-without-stretching",
    "jpg-vs-png",
  ],
  "canva-vs-pixores": [
    "create-youtube-thumbnail-free",
    "how-to-create-youtube-thumbnail",
    "thumbnail-color-psychology",
    "youtube-thumbnail-ab-testing",
  ],
};
