const { contextBridge, ipcRenderer } = require("electron");

const PIXORES_DESKTOP_CHANNELS = Object.freeze({
  assetsImport: "pixores:assets:import",
  assetsChooseProjectFolder: "pixores:assets:choose-project-folder",
  assetsCopyToProject: "pixores:assets:copy-to-project",
  projectPackageOpen: "pixores:project-package:open",
  projectPackageOpenRecent: "pixores:project-package:open-recent",
  projectPackageSave: "pixores:project-package:save",
  projectPackageRecentList: "pixores:project-package:recent-list",
  projectPackageRecentSave: "pixores:project-package:recent-save",
  projectPackageRecentAdd: "pixores:project-package:recent-add",
  projectPackageRecentRemove: "pixores:project-package:recent-remove",
  projectPackageRecentRename: "pixores:project-package:recent-rename",
  projectPackageRecentDuplicate: "pixores:project-package:recent-duplicate",
  projectOpen: "pixores:project:open",
  projectSave: "pixores:project:save",
  licenseStatusGet: "pixores:license:get-status",
  licenseStatusSave: "pixores:license:save-status",
  licenseStatusClear: "pixores:license:clear-status",
  updateCheck: "pixores:update:check",
  updateDownload: "pixores:update:download",
  updateInstall: "pixores:update:install",
  renderVideoLocal: "pixores:render:video-local",
  renderStart: "pixores:render:start",
  renderStatus: "pixores:render:status",
});

contextBridge.exposeInMainWorld("pixoresDesktop", {
  importAsset: (payload) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.assetsImport, payload),
  chooseProjectFolder: (payload) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.assetsChooseProjectFolder, payload),
  copyAssetToProject: (payload) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.assetsCopyToProject, payload),
  openProjectPackage: () => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageOpen),
  openRecentProjectPackage: (filePath) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageOpenRecent, filePath),
  saveProjectPackage: (payload) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageSave, payload),
  getRecentProjects: () => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageRecentList),
  addRecentProject: (project) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageRecentAdd, project),
  saveRecentProject: (project) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageRecentSave, project),
  removeRecentProject: (filePath) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageRecentRemove, filePath),
  renameRecentProject: (payload) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageRecentRename, payload),
  duplicateRecentProject: (filePath) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectPackageRecentDuplicate, filePath),
  openProject: () => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectOpen),
  saveProject: (payload) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.projectSave, payload),
  getLicenseStatus: () => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.licenseStatusGet),
  saveLicenseStatus: (input) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.licenseStatusSave, input),
  clearLicenseStatus: () => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.licenseStatusClear),
  checkForUpdates: () => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.updateCheck),
  downloadUpdate: () => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.updateDownload),
  installUpdate: () => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.updateInstall),
  renderVideoLocal: (project, options) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.renderVideoLocal, project, options),
  startRender: (project, options) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.renderStart, project, options),
  getRenderStatus: (renderId) => ipcRenderer.invoke(PIXORES_DESKTOP_CHANNELS.renderStatus, renderId),
});
